### ISSUE TITLE
Update to Freemarker 2.3.23

### ISSUE THREAD

**Issue by plaa** [jbosstools/jbosstools-freemarker#48]
Please update the package to use Freemarker 2.3.23.  I'm using the new "entry?index" format of #list (http://freemarker.org/docs/ref_builtins_loop_var.html), and the IDE is producing an error that's putting the entire project in the red.  I haven't figured any way to prevent the IDE from validating the ftl files either.

**Comment by alexeykazakov** [comment]
This one was fixed.
